[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
  [context.deploy-preview]
    ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"
publish = ".next"
[context.deploy-preview]
ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"